name: Web CD(development)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Set the environment to deploy"
        type: "environment"
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ inputs.environment }}
