name: Web CD(development)

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Set the environment to deploy"
        required: true
        default: ""
        type: "choice"
        options:
          - dev
          - qa
          - prod

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: DEPLOY_ENV=${{ inputs.deploy_env }} || 'dev' && echo $DEPLOY_ENV
