name: Web CD(development)

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Set the environment to deploy"
        required: true
        default: ""
        type: "choice"
        options:
          - dev
          - qa
          - prod

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: get-env.sh test
        run: | 
          chmod +x get-env.sh
          DEPOLY_ENV=$(get-env.sh "${{ inputs.deploy_env }}")
          echo DEPLOY_ENV
      - run: DEPLOY_ENV=${{ inputs.deploy_env }} && DEPLOY_ENV=$($DEPLOY_ENV || 'dev') && echo $DEPLOY_ENV
