name: Web CD(development)

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Set the environment to deploy"
        required: true
        default: ""
        type: "choice"
        options:
          - dev
          - qa
          - prod

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: get-env.sh test
        run: | 
          chmod +x ./.github/scripts/get-env.sh
          ./.github/scripts/get-env.sh "${{ inputs.deploy_env }}"
          DEPOLY_ENV=$(./.github/scripts/get-env.sh "${{ inputs.deploy_env }}")
          echo "$DEPOLY_ENV"
