name: Web CD(development)

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Set the environment to deploy"
        required: true
        default: "dev"
        type: "choice"
        options:
          - dev
          - qa
          - prod

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ inputs.environment }}
