name: Web CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
#    env:
#      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn --prefer-offline
      - name: Build web code
        run: yarn run build --filter=web... --team="sloth19" --token="sqjBUqFcGLm77wPT05CtiuiF"